In [2]:
import numpy as np

In [3]:
eye = np.eye(4)

In [7]:
print('Matrix Eye:\n{}'.format(eye))
# el metodo 'eye', nos permite crear una matriz con una diagonal de unos y el resto de datos ceros
# solo debe ingresar un parametro, toma este parametro en ambas dimensiones; genera una matriz con row's and column's iguales.

Matrix Eye:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
