<a href="https://colab.research.google.com/github/Jean-Rd/Algoritms_Intro_machineLearningWithPython/blob/master/Basico_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [3]:
SEED = 1234

np.random.seed(seed=SEED)

torch.manual_seed(SEED)

In [6]:
a = torch.rand(3,2)

a.reshape(2,3)

tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])

In [12]:
a.type()

a.long()

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [14]:
b = torch.zeros(5,4)

b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
c = torch.ones(5,3)

a

tensor([[0.7749, 0.8208],
        [0.2793, 0.6817],
        [0.2837, 0.6567]])

In [28]:
d = torch.Tensor(np.array([[2,3,4],[4,5,6]]))

e

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [22]:
e = torch.Tensor(np.array([[1,2,3],[5,6,7]]))

e+d

tensor([[ 3.,  5.,  7.],
        [ 9., 11., 13.]])

In [27]:
d.T

tensor([[2., 4.],
        [3., 5.],
        [4., 6.]])

In [26]:
torch.mm(e,d.T)

tensor([[20., 32.],
        [56., 92.]])

In [34]:
d.view(3,2)

tensor([[2., 3.],
        [4., 4.],
        [5., 6.]])

In [36]:
a

tensor([[0.7749, 0.8208],
        [0.2793, 0.6817],
        [0.2837, 0.6567]])

In [37]:
torch.sum(a, dim=1)

tensor([1.5957, 0.9610, 0.9404])

In [38]:
torch.sum(a, dim=0)

tensor([1.3378, 2.1592])

In [41]:
x = torch.rand(3,4)

x

tensor([[0.6662, 0.3343, 0.7893, 0.3216],
        [0.5247, 0.6688, 0.8436, 0.4265],
        [0.9561, 0.0770, 0.4108, 0.0014]])

In [43]:
x[1:2]

tensor([[0.5247, 0.6688, 0.8436, 0.4265]])

In [44]:
x[1:3, 2:3]

tensor([[0.8436],
        [0.4108]])

In [50]:
select = torch.LongTensor([0,2])

torch.index_select(x, dim=1, index=select)

tensor([[0.6662, 0.7893],
        [0.5247, 0.8436],
        [0.9561, 0.4108]])

In [51]:
torch.index_select(x, dim=0, index=select)

tensor([[0.6662, 0.3343, 0.7893, 0.3216],
        [0.9561, 0.0770, 0.4108, 0.0014]])

In [53]:
x[[0,1], [0,2]]

tensor([0.6662, 0.8436])

In [56]:
torch.cat([x,x], dim=1)

tensor([[0.6662, 0.3343, 0.7893, 0.3216, 0.6662, 0.3343, 0.7893, 0.3216],
        [0.5247, 0.6688, 0.8436, 0.4265, 0.5247, 0.6688, 0.8436, 0.4265],
        [0.9561, 0.0770, 0.4108, 0.0014, 0.9561, 0.0770, 0.4108, 0.0014]])

In [58]:
torch.cat([x,x], dim=0)

tensor([[0.6662, 0.3343, 0.7893, 0.3216],
        [0.5247, 0.6688, 0.8436, 0.4265],
        [0.9561, 0.0770, 0.4108, 0.0014],
        [0.6662, 0.3343, 0.7893, 0.3216],
        [0.5247, 0.6688, 0.8436, 0.4265],
        [0.9561, 0.0770, 0.4108, 0.0014]])

In [76]:
x = torch.rand(3,4, requires_grad=True)

y = 3*x + 2

z = y.mean()

z.backward()

In [78]:
x.grad, x

(tensor([[0.2500, 0.2500, 0.2500, 0.2500],
         [0.2500, 0.2500, 0.2500, 0.2500],
         [0.2500, 0.2500, 0.2500, 0.2500]]),
 tensor([[7.4271e-01, 4.4390e-02, 8.5979e-01, 4.0278e-01],
         [8.7121e-01, 2.0658e-01, 2.4565e-02, 1.6854e-01],
         [4.2249e-01, 6.3777e-04, 4.6593e-01, 2.5046e-01]], requires_grad=True))

In [79]:
print(torch.cuda.is_available())

False
