<a href="https://colab.research.google.com/github/Jean-Rd/Algoritms_Intro_machineLearningWithPython/blob/master/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np

model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
'''
tf.keras.Sequential([]) --> creamos la red neuronal
IN TO keras.layers.Dense() --> esto es una capa oculta
  IN TO units = --> numero de neuronas de la capa
  IN TO input_shape=[] --> la dimension del input 
'''

model.compile(optimizer='sgd', loss='mean_squared_error')
'''
model.compile() --> definiendo parametros del model 
IN TO optimizer = '' --> definiendo la funcion que reducira la perdida en este caso decenso del gradiente esocastico 'sgd'
IN TO loss = '' --> definiendo la funcion que calculara la perdida de cada neurona en este caso 'mse'
'''

# DATA

xs = np.array([-1.0,0.0,1.0,2.0,3.0,4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)

# TRIN

model.fit(xs, ys, epochs=500)
'''
model.fit() --> entrena al modelo y calcula la perdida y la optimizacion que declaramos anteriormente para cada epoca(epochs)
IN TO model.fit(xs, ys, epochs=) --> X_data, y_data, epocas
'''

Epoch 1/500
1/1 [==============================] - 0s 1ms/step - loss: 70.8316
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 55.7278
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 43.8447
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 34.4957
Epoch 5/500
1/1 [==============================] - 0s 1ms/step - loss: 27.1403
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 21.3535
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 16.8006
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 13.2186
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 10.4005
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 8.1833
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 6.4389
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 5.0665
Epoch 13/500
1/1 [==============================] - 

'\nmodel.fit() --> entrena al modelo y calcula la perdida y la optimizacion que declaramos anteriormente para cada epoca(epochs)\nIN TO model.fit(xs, ys, epochs=) --> X_data, y_data, epocas\n'

In [ ]:
# PREDICT

model.predict([10.0])

array([[30.998919]], dtype=float32)

In [ ]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np


model_v1 = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

model_v1.compile(optimizer='sgd', loss='mean_squared_error')

_X = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], dtype=float)
_y = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0], dtype=float)

model_v1.fit(_X, _y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 1ms/step - loss: 50.6091
Epoch 2/2000
1/1 [==============================] - 0s 811us/step - loss: 23.1479
Epoch 3/2000
1/1 [==============================] - 0s 910us/step - loss: 10.6391
Epoch 4/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.9404
Epoch 5/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.3434
Epoch 6/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.1591
Epoch 7/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6182
Epoch 8/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3704
Epoch 9/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2561
Epoch 10/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2026
Epoch 11/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1768
Epoch 12/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1637
Epoch 13/2000
1/1 [=======================

In [ ]:

model_v1.predict([10.0])


#2.27 * np.array([-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0], dtype=float)

array([[-1.0000032]], dtype=float32)

In [ ]:
modelV2 = tf.keras.Sequential([keras.layers.Dense(units=2, input_shape=[1])])

modelV2.compile(optimizer='sgd', loss='mean_squared_error')

x = np.array([-7.0,-6.0,-5.0,-4.0,-3.0,-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0], dtype=float)
y = np.array([-19.0279728 , -16.30969097, -13.59140914, -10.87312731,
        -8.15484549,  -5.43656366,  -2.71828183,   0.        ,
         2.71828183,   5.43656366,   8.15484549,  10.87312731,
        13.59140914,  16.30969097,  19.0279728 ], dtype=float)

In [ ]:
modelV2.fit(x, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 1ms/step - loss: 108.0422
Epoch 2/2000
1/1 [==============================] - 0s 1ms/step - loss: 71.4711
Epoch 3/2000
1/1 [==============================] - 0s 863us/step - loss: 47.2789
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.2755
Epoch 5/2000
1/1 [==============================] - 0s 878us/step - loss: 20.6891
Epoch 6/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.6861
Epoch 7/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.0535
Epoch 8/2000
1/1 [==============================] - 0s 2ms/step - loss: 5.9890
Epoch 9/2000
1/1 [==============================] - 0s 1ms/step - loss: 3.9618
Epoch 10/2000
1/1 [==============================] - 0s 1ms/step - loss: 2.6208
Epoch 11/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.7337
Epoch 12/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.1468
Epoch 13/2000
1/1 [===================

In [ ]:
modelV2.predict([10.0])

array([[27.182812, 27.182812]], dtype=float32)

In [ ]:
modelV3 = tf.keras.Sequential([keras.layers.Dense(units=3, input_shape=[1])])

y3 = (x * np.e) / np.pi

modelV3.compile(optimizer='sgd', loss='mean_squared_error')

modelV3.fit(x, y3, epochs= 1500)

Epoch 1/1500
1/1 [==============================] - 0s 1ms/step - loss: 33.3162
Epoch 2/1500
1/1 [==============================] - 0s 864us/step - loss: 25.5401
Epoch 3/1500
1/1 [==============================] - 0s 1ms/step - loss: 19.5790
Epoch 4/1500
1/1 [==============================] - 0s 2ms/step - loss: 15.0092
Epoch 5/1500
1/1 [==============================] - 0s 2ms/step - loss: 11.5060
Epoch 6/1500
1/1 [==============================] - 0s 2ms/step - loss: 8.8205
Epoch 7/1500
1/1 [==============================] - 0s 2ms/step - loss: 6.7618
Epoch 8/1500
1/1 [==============================] - 0s 2ms/step - loss: 5.1836
Epoch 9/1500
1/1 [==============================] - 0s 2ms/step - loss: 3.9737
Epoch 10/1500
1/1 [==============================] - 0s 1ms/step - loss: 3.0462
Epoch 11/1500
1/1 [==============================] - 0s 861us/step - loss: 2.3352
Epoch 12/1500
1/1 [==============================] - 0s 870us/step - loss: 1.7902
Epoch 13/1500
1/1 [===================

In [ ]:
modelV3.predict([10.0])

array([[8.652557, 8.652557, 8.652557]], dtype=float32)

In [ ]:
y = 1/(1 + np.e**-x)

modelV4 = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
modelV4.compile(optimizer='sgd', loss='mean_squared_error')

modelV4.fit(x, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 1ms/step - loss: 4.1394
Epoch 2/2000
1/1 [==============================] - 0s 831us/step - loss: 1.7777
Epoch 3/2000
1/1 [==============================] - 0s 860us/step - loss: 0.8447
Epoch 4/2000
1/1 [==============================] - 0s 796us/step - loss: 0.4729
Epoch 5/2000
1/1 [==============================] - 0s 781us/step - loss: 0.3217
Epoch 6/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2573
Epoch 7/2000
1/1 [==============================] - 0s 835us/step - loss: 0.2272
Epoch 8/2000
1/1 [==============================] - 0s 871us/step - loss: 0.2109
Epoch 9/2000
1/1 [==============================] - 0s 890us/step - loss: 0.2000
Epoch 10/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1915
Epoch 11/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1841
Epoch 12/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1773
Epoch 13/2000
1/1 [================

In [ ]:
modelV4.predict([10.0])

array([[1.444553]], dtype=float32)

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

modelV = tf.keras.Sequential(keras.layers.Dense(units=1, input_shape=[1]))

modelV.compile(optimizer='sgd', loss='mean_squared_error')

x = np.array([1,2,3,4,5,6], dtype=float)
y = np.array([23, 24, 25, 26, 27, 28], dtype=float)

modelV.fit(x, y, epochs=700)

Epoch 1/700
1/1 [==============================] - 0s 1ms/step - loss: 870.6016
Epoch 2/700
1/1 [==============================] - 0s 1ms/step - loss: 445.3757
Epoch 3/700
1/1 [==============================] - 0s 2ms/step - loss: 248.2593
Epoch 4/700
1/1 [==============================] - 0s 2ms/step - loss: 156.7209
Epoch 5/700
1/1 [==============================] - 0s 2ms/step - loss: 114.0496
Epoch 6/700
1/1 [==============================] - 0s 1ms/step - loss: 93.9975
Epoch 7/700
1/1 [==============================] - 0s 2ms/step - loss: 84.4166
Epoch 8/700
1/1 [==============================] - 0s 2ms/step - loss: 79.6842
Epoch 9/700
1/1 [==============================] - 0s 1ms/step - loss: 77.1980
Epoch 10/700
1/1 [==============================] - 0s 2ms/step - loss: 75.7535
Epoch 11/700
1/1 [==============================] - 0s 1ms/step - loss: 74.7934
Epoch 12/700
1/1 [==============================] - 0s 2ms/step - loss: 74.0596
Epoch 13/700
1/1 [==========================

In [ ]:
modelV.predict([10.0])

array([[34.10811]], dtype=float32)